title: Minvamos
logo: /assets/img/Selfi.jpg
email: zzmsz0317@gmail.com
description: 학부생 개발일지/n 서울과학기술대학교 전기정보공학과
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/minvamos
  - name: Instagram
    icon: <i class="fa-brands fa-instagram"></i>
    link: https://www.instagram.com/minvamos_

navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
    
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

